print ("Checking Modules")
print ("If a error use setup.py")
print ("Thank you for use my tool")
import os 
print ("Startig Nikto")
print ("Startig Nikto.")
print ("Startig Nikto..")
print ("Startig Nikto...")
os.system("sudo apt install nikto && apk add nikto && pkg install nikto && clear && figlet Nikto")  
site_nikto = input("Enter Site Target:")
os.system(f"nikto -h {site_nikto}")